from utilities.item import Item

def getItems():
    return [
        Item("Timbsit", "Rakennettu rymyämiseen ja vauhtiin.", speedMod=["mult", 1.5]),
        Item("Terveysjuoma", "Epäilyttävän punainen neste pulloissa.", healthCapMult=["mult", 1.35]),
        Item("Ylikellotus", "Täl lähtee kyl jo käsi irti.", weaponFireRate=["mult", 1.5]),
        Item("Ase-ekspertti", "Elä opeta isääs paneen.", weaponDamage=["mult", 1.4], weaponHandling=["mult", 1.25], weaponReload=["add", -0.25]),
        Item("Berserker", "Holtittomuus toimii.", berserker=["set", True]),
        Item("God is king", "Usko niin pelastut.", saveChance=["add", 0.05]),
        Item("Lasersääntö", "Älä ny omia ammu.", allyProtection=["set", True]),
        Item("Paskahousu", "Pelottaa nii perkelleesti.", coward=["set", True]),
        Item("Kevut", "Suojaa kineettisiltä vahingolta.", defenceNormal=["mult", 2], defenceExplosion=["mult", 1.5]),
        Item("Adrenaliiniruiske", "HP:t nousee silmissä.", instaHeal=["set", True]),
        Item("Martyrdom", "Ni.", martyrdom=["set", True]),
        Item("Masokismi", "Minun kipu on sinun kipu.", thorns=["add", 0.25], weaponFireRate=["add", 0.5], healthCapMult=["mult", 1.25]),
        Item("Replikaattori", "Kopiointi kannattaa.", duplicator=["set", True]),
        Item("Rage", "Vitutus on voimaa.", fireRateIncrease=["add", 5]),
        Item("Romupanssari", "Teipillä ja toivolla koottu.", defenceNormal=["mult", 1.5], speedMod=["mult", 0.85]),
        Item("Cryo-puku", "Suojaa hyvin energia-ammuksilta.", defenceEnergy=["mult", 2], speedMod=["mult", 0.8]),
        Item("Kosto elää", "Mä tuun tappaan sut kohta...", revenge=["set", True]),
        Item("Neurosynkronointi", "Ase vispaa ampuessa muttei ladatessa.", weaponHandling=["mult", 1.6], weaponReload=["mult", 0.75]),
        Item("Rumpulipas", "Gangstashittii.", weaponAmmoCap=["mult", 2.0], weaponFireRate=["mult", 0.8]),
        Item("Adderall", "Ylivilkas ja hauras.", weaponHandling=["mult", 2], speedMod=["mult", 1.25], weaponReload=["mult", 0.75], healthCapMult=["mult", 0.5]),
        Item("Dodge Charger", "Emmää ees myy huumeita.", dodgeChance=["add", 0.15], speedMod=["mult", 1.2]),
        Item("Adrenaalimutageeni", "Tappaminen virkistää.", healOnKill=["add", 25], healthCapMult=["mult", 0.8]),
        Item("Sotasaalis", "Tämä on ansaittu.", xpMult=["add", 0.5]),
        Item("Liiketunnistin", "Kukaan ei piiloudu pitkään.", weaponRange=["add", 0.25]),
        Item("Ruostevaimennin", "Paska mutta toimii.", accuracy=["mult", 0.7], weaponDamage=["mult", 1.25]),
        Item("Nanopehmuste", "Pehmentää iskut.", knockbackMult=["mult", 2], speedMod=["mult", 0.9]),
        Item("Hemostim", "Parantaa kesken taistelun.", healthRegenMult=["add", 0.25], instaHeal=["set", True]),
        Item("Tukituli", "Luoteja viuhuu.", weaponFireRate=["mult", 1.5], healthCapMult=["mult", 0.75]),
        Item("Verenhimoprosessori", "Tekis mieli ampua sut saatana...", healOnKill=["add", 40], berserker=["set", True]),
        Item("Ammuskompaktori", "Panokset vievät vähemmän tilaa.", weaponAmmoCap=["mult", 3.0], weaponReload=["mult", 0.7]),
        Item("Satelliittivalvonta", "Täält ylhäältä näkyy kaikki.", weaponRange=["add", 0.2], defenceNormal=["mult", 0.9]),
        Item("Kelan työttömyysturva", "Jälkeenjääneille.", xpMult=["mult", 1.5], weaponHandling=["mult", 0.5], speedMod=["mult", 0.6]),
        Item("Lasikanuuna", "4750$.", weaponDamage=["mult", 2], healthCapMult=["mult", 0.5]),
        Item("Tuplatusautus", "Kaksi kutii yhden hinnalla.", multiShot=["add", 1]),
        Item("Sleight of hand", "Niiku Kodissa.", weaponReload=["mult", 2]),
        Item("Tulkutus", "Kaunis äänesi on kuultavA.", talking=["set", True]),
        Item("Petturi", "Lojaalisuus on lusmuille.", turnCoat=["set", True]),
        Item("Sahattu Piippu", "Sohii mutta toimii.", weaponDamage=["mult", 2], accuracy=["mult", 0.5]),
        Item("Silmälasit", "Nelisilmä", accuracy=["add", 0.25], weaponHandling=["mult", 0.75]),
        Item("Paholaisien munat", "On muuten isot", saveChance=["add", -0.1], healthCapMult=["mult", 0.8], speedMod=["add", 0.2], weaponDamage=["add", 0.25]),
        Item("Virkalakki", "Erittäin fiini.", hat=["set", True], defenceEnergy=["mult", 1.5], defenceNormal=["mult", 1.5], defenceExplosion=["mult", 1.5]),
        Item("360", "Maken vlikki", noscoping=["set", True], weaponDamage=["mult", 1.5], weaponHandling=["mult", 1.2]),
        Item("Latexpuku", "Eristää energialta, extrafriikeille.", defenceEnergy=["mult", 1.4], speedMod = ["mult", 0.85]),
        Item("Pistin", "Tuikkaa astetta kovemmin.", meleeDamage=["add", 0.25], weaponHandling=["mult", 0.9]),
        Item("Compressor", "Pibgistä tuttu.", recoilMult = ["mult", 2]),
        Item("Flash hider", "Pibgistä tuttu.", recoilMult = ["mult", 1.5], weaponDamage=["add", 0.2]),
        Item("AP-Luodit", "Kun äijät ampuu vihuja nii omat on vaa tiellä.", piercing=["set", True]),
        Item("Litra mälliä", "Jos sulle maksettais kaks sataa...", healthCapMult=["add", 0.5]),
        Item("Rauhan uskonto", "Rauha on paras ase.", detonation=["set", True], defenceExplosion=["mult", 5]),
        Item("Tankki", "Nää ei oo niitä nopeimpia kavereita.", speedMod=["mult", 0.5], healthCapMult=["mult", 2]),
        Item("Kivimies", "Kivimies on kova mies.", tripChance=["add", 0.1], defenceNormal=["mult", 3], defenceEnergy=["mult", 3], defenceExplosion=["mult", 3]),
    ]



itemEffects = {
    "speedMod": 1.0, # Done
    "healthRegenMult": 1.0,
    "thorns": 0.0,
    "healthCapMult": 1.0,
    "berserker" : False,
    "martyrdom" : False,

    "weaponHandling" : 1.0,
    "weaponDamage" : 1.0,
    "weaponReload" : 1.0,
    "weaponFireRate" : 1.0,
    "weaponAmmoCap" : 1.0,
    "weaponRange":1.0,
    "accuracy":1.0,

    "instaHeal" : False,
    "saveChance" : 0.0,
    "fireRateIncrease" : 0,
    "allyProtection" : False,
    "coward" : False,
    "revenge" : False,
    "duplicator" : False,

    "defenceNormal" : 1.0,
    "defenceEnergy" : 1.0,
    "defenceExplosion" : 1.0,

    "dodgeChance": 0.0,
    "xpMult":1.0,
    "healOnKill":0.0,
    "knockBackMult":1.0,
    "healAllies":0.0

}