from utilities.item import Item

def getItems():
    return [
        Item("Timbsit", "Rakennettu rymyämiseen ja vauhtiin.", speedMod=["mult", 1.5]),
        Item("Terveysjuoma", "Epäilyttävän punainen neste pulloissa.", healthCapMult=["mult", 1.35]),
        Item("Ylikellotus", "Täl lähtee kyl jo käsi irti.", weaponFireRate=["mult", 1.5]),
        Item("Ase-ekspertti", "Elä opeta isääs paneen.", weaponDamage=["mult", 1.4], weaponHandling=["mult", 1.25], weaponReload=["add", -0.25]),
        Item("Berserker", "Holtittomuus toimii.", berserker=["set", True]),
        Item("God is king", "Usko niin pelastut.", saveChance=["add", 0.05]),
        Item("Lasersääntö", "Älä ny omia ammu.", allyProtection=["set", True]),
        Item("Pelkuri", "Pelottaa nii perkelleesti.", coward=["set", True]),
        Item("Kevut", "Suojaa kineettisiltä vahingolta.", defenceNormal=["mult", 2], defenceExplosion=["mult", 1.5]),
        Item("Adrenaliiniruiske", "HP:t nousee silmissä.", instaHeal=["set", True]),
        Item("Martyrdom", "Ni.", martyrdom=["set", True]),
        Item("Masokismi", "Minun kipu on sinun kipu.", thorns=["add", 0.25], weaponFireRate=["add", 0.5], healthCapMult=["mult", 1.25]),
        Item("Sadismi", "Sun kipu on mun ilo.", lifeSteal=["add", 0.25], weaponDamage=["mult", 1.1], healthCapMult=["mult", 1.15]),
        Item("Rage", "Vitutus on voimaa.", fireRateIncrease=["add", 5]),
        Item("Romupanssari", "Teipillä ja toivolla koottu.", defenceNormal=["mult", 1.5], speedMod=["mult", 0.85]),
        Item("Cryo-puku", "Suojaa hyvin energia-ammuksilta.", defenceEnergy=["mult", 2], speedMod=["mult", 0.8]),
        Item("Kosto elää", "Mä tuun tappaan sut kohta...", revenge=["set", True]),
        Item("Neurosynkronointi", "Ase vispaa ampuessa muttei ladatessa.", weaponHandling=["mult", 1.6], weaponReload=["mult", 0.75]),
        Item("Rumpulipas", "Gangstashittii.", weaponAmmoCap=["mult", 2.0], weaponFireRate=["mult", 0.8]),
        Item("Adderall", "Ylivilkas ja hauras.", weaponHandling=["mult", 2], speedMod=["mult", 1.25], weaponReload=["mult", 0.75], healthCapMult=["mult", 0.5]),
        Item("Dodge Charger", "Emmää ees myy huumeita.", dodgeChance=["add", 0.2], speedMod=["mult", 1.2]),
        Item("Adrenaalimutageeni", "Tappaminen virkistää.", healOnKill=["add", 25], healthCapMult=["mult", 0.8]),
        Item("Sotasaalis", "Tämä on ansaittu.", xpMult=["add", 0.5]),
        Item("Liiketunnistin", "Kukaan ei piiloudu pitkään.", weaponRange=["add", 0.5]),
        Item("Ruostevaimennin", "Paska mutta toimii.", accuracy=["mult", 0.7], weaponDamage=["mult", 1.25]),
        Item("Nanopehmuste", "Pehmentää iskut.", knockbackMult=["mult", 2], speedMod=["mult", 0.9]),
        Item("Hemostim", "Parantaa kesken taistelun.", healthRegenMult=["add", 0.25], instaHeal=["set", True]),
        Item("Tukituli", "Luoteja viuhuu.", weaponFireRate=["mult", 1.5], healthCapMult=["mult", 0.75]),
        Item("Verenhimoprosessori", "Tekis mieli ampua sut saatana...", healOnKill=["add", 40], berserker=["set", True]),
        Item("Ammuskompaktori", "Panokset vievät vähemmän tilaa.", weaponAmmoCap=["mult", 3.0], weaponReload=["mult", 0.7]),
        Item("Satelliittivalvonta", "Täält ylhäältä näkyy kaikki.", weaponRange=["add", 0.2], defenceNormal=["mult", 1.1]),
        Item("Kelan työttömyysturva", "Jälkeenjääneille.", xpMult=["mult", 5], weaponHandling=["mult", 0.5], speedMod=["mult", 0.6]),
        Item("Lasikanuuna", "4750$.", weaponDamage=["mult", 2], healthCapMult=["mult", 0.5]),
        Item("Tuplatusautus", "Kaksi kutii yhden hinnalla.", multiShot=["add", 1]),
        Item("Sleight of hand", "Niiku Kodissa.", weaponReload=["mult", 2]),
        Item("Tulkutus", "Kaunis äänesi on kuultavA.", talking=["set", True]),
        Item("Petturi", "Lojaalisuus on lusmuille.", turnCoat=["set", True]),
        Item("Sahattu Piippu", "Sohii mutta toimii.", weaponDamage=["mult", 2], accuracy=["mult", 0.5]),
        Item("Silmälasit", "Nelisilmä", accuracy=["add", 0.25], weaponHandling=["mult", 0.75]),
        Item("Paholaisien munat", "On muuten isot", saveChance=["add", -0.1], healthCapMult=["mult", 0.8], speedMod=["add", 0.2], weaponDamage=["add", 0.25]),
        Item("Virkalakki", "Erittäin fiini.", hat=["set", True], defenceEnergy=["mult", 1.5], defenceNormal=["mult", 1.5], defenceExplosion=["mult", 1.5]),
        Item("360", "Maken vlikki", noscoping=["set", True], weaponDamage=["mult", 1.5], weaponHandling=["mult", 1.2]),
        Item("Latexpuku", "Eristää energialta, extrafriikeille.", defenceEnergy=["mult", 1.4], speedMod = ["mult", 0.85]),
        Item("Pistin", "Tuikkaa astetta kovemmin.", meleeDamage=["add", 0.25], weaponHandling=["mult", 0.9]),
        Item("Compressor", "Pibgistä tuttu.", recoilMult = ["mult", 2]),
        Item("Flash hider", "Pibgistä tuttu.", recoilMult = ["mult", 1.5], weaponDamage=["add", 0.2]),
        Item("Suppressori", "Pibgistä tuttu.", recoilMult = ["mult", 2], weaponDamage=["add", -0.1]),
        Item("AP-Luodit", "Kun äijät ampuu vihuja nii omat on vaa tiellä.", piercing=["set", True]),
        Item("Litra mälliä", "Jos sulle maksettais kaks sataa...", healthCapMult=["add", 0.5]),
        Item("Rauhan uskonto", "Rauha on paras ase.", detonation=["set", True], defenceExplosion=["mult", 5]),
        Item("Tankki", "Nää ei oo niitä nopeimpia kavereita.", speedMod=["mult", 0.5], healthCapMult=["mult", 2]),
        Item("Kivimies", "Kivimies on kova mies.", tripChance=["add", 0.01], defenceNormal=["mult", 3], defenceEnergy=["mult", 3], defenceExplosion=["mult", 3]),
        Item("Niken Nyssykkä", "Voi tätä valinnan vaikeutta.", extraItem=["set", True]),
        Item("Magneetti", "Miten ne toimii?", homing=["set", True], weaponDamage=["mult", 0.75]),
        Item("Paskahousu", "Nyt täytyy mennä varovasti", shitChance=["add", 0.025], speedMod=["mult", 0.9], healthCapMult=["mult", 1.1]),
        Item("Tuplaruuti", "Pyssy potkii pirusti", recoilMult=["mult", 0.25], weaponDamage=["mult", 2]),
        Item("Mankka", "Bulgarian pop idol", playMusic=["set", True], dodgeChance=["add", 0.3]),
        Item("Mersun merkki", "Visva. Saatana.", speedMod=["mult", 1.25]),
        Item("Taktinen juoksu", "Hvarin poliisi belike", tacticalSprintSpeed=["mult", 3]),
        Item("VAC", "Rupee koodarit jäämää.", bossKiller=["set", True])
        #Item("Mag dump", "Mikä vitun firerate", magDump=["set", True]),
    ]


def getItemsEng():
    return [
        Item("Timbs", "Built for stomping and speed.", speedMod=["mult", 1.5]),
        Item("Health Drink", "Suspiciously red liquid in bottles.", healthCapMult=["mult", 1.35]),
        Item("Overclocking", "This'll make your arm fly off.", weaponFireRate=["mult", 1.5]),
        Item("Gun Expert", "Don't teach your dad how to screw.", weaponDamage=["mult", 1.4], weaponHandling=["mult", 1.25], weaponReload=["add", -0.25]),
        Item("Berserker", "Recklessness works.", berserker=["set", True]),
        Item("God is king", "Believe and you'll be saved.", saveChance=["add", 0.05]),
        Item("Laser Rule", "Don't shoot your own.", allyProtection=["set", True]),
        Item("Coward", "Scared shitless.", coward=["set", True]),
        Item("Kevlar", "Protects against kinetic damage.", defenceNormal=["mult", 2], defenceExplosion=["mult", 1.5]),
        Item("Adrenaline Shot", "Your HP rises before your eyes.", instaHeal=["set", True]),
        Item("Martyrdom", "Yep.", martyrdom=["set", True]),
        Item("Masochism", "My pain is your pain.", thorns=["add", 0.25], weaponFireRate=["add", 0.5], healthCapMult=["mult", 1.25]),
        Item("Rage", "Anger is power.", fireRateIncrease=["add", 5]),
        Item("Junk Armor", "Held together with tape and hope.", defenceNormal=["mult", 1.5], speedMod=["mult", 0.85]),
        Item("Cryo-suit", "Protects well against energy ammo.", defenceEnergy=["mult", 2], speedMod=["mult", 0.8]),
        Item("Revenge Lives", "I'm gonna kill you soon…", revenge=["set", True]),
        Item("Neurosynchronization", "Gun rattles while firing but not while reloading.", weaponHandling=["mult", 1.6], weaponReload=["mult", 0.75]),
        Item("Drum Magazine", "Gangsta shit.", weaponAmmoCap=["mult", 2.0], weaponFireRate=["mult", 0.8]),
        Item("Adderall", "Hyperactive and fragile.", weaponHandling=["mult", 2], speedMod=["mult", 1.25], weaponReload=["mult", 0.75], healthCapMult=["mult", 0.5]),
        Item("Dodge Charger", "I don't even sell drugs.", dodgeChance=["add", 0.15], speedMod=["mult", 1.2]),
        Item("Adrenaline Mutagen", "Killing refreshes you.", healOnKill=["add", 25], healthCapMult=["mult", 0.8]),
        Item("Spoils of War", "This is deserved.", xpMult=["add", 0.5]),
        Item("Motion Sensor", "No one hides for long.", weaponRange=["add", 0.25]),
        Item("Rust Suppressor", "Shit but it works.", accuracy=["mult", 0.7], weaponDamage=["mult", 1.25]),
        Item("Nano Padding", "Softens the blows.", knockbackMult=["mult", 2], speedMod=["mult", 0.9]),
        Item("Hemostim", "Heals mid-fight.", healthRegenMult=["add", 0.25], instaHeal=["set", True]),
        Item("Suppressive Fire", "Bullets whizz everywhere.", weaponFireRate=["mult", 1.5], healthCapMult=["mult", 0.75]),
        Item("Bloodlust Processor", "Makes you wanna shoot, damn it…", healOnKill=["add", 40], berserker=["set", True]),
        Item("Ammo Compactor", "Bullets take less space.", weaponAmmoCap=["mult", 3.0], weaponReload=["mult", 0.7]),
        Item("Satellite Surveillance", "From up here, everything is visible.", weaponRange=["add", 0.2], defenceNormal=["mult", 0.9]),
        Item("Unemployment Benefits", "For the left-behind.", xpMult=["mult", 5], weaponHandling=["mult", 0.5], speedMod=["mult", 0.6]),
        Item("Glass Cannon", "$4750.", weaponDamage=["mult", 2], healthCapMult=["mult", 0.5]),
        Item("Double Trouble", "Two shots for the price of one.", multiShot=["add", 1]),
        Item("Sleight of Hand", "Like in CoD.", weaponReload=["mult", 2]),
        Item("Yelling", "Your beautiful voice will be heard.", talking=["set", True]),
        Item("Traitor", "Loyalty is for slackers.", turnCoat=["set", True]),
        Item("Sawn-off", "Messy but effective.", weaponDamage=["mult", 2], accuracy=["mult", 0.5]),
        Item("Glasses", "Four-eyes.", accuracy=["add", 0.25], weaponHandling=["mult", 0.75]),
        Item("Devil's Balls", "They're huge.", saveChance=["add", -0.1], healthCapMult=["mult", 0.8], speedMod=["add", 0.2], weaponDamage=["add", 0.25]),
        Item("Police Cap", "Very fancy.", hat=["set", True], defenceEnergy=["mult", 1.5], defenceNormal=["mult", 1.5], defenceExplosion=["mult", 1.5]),
        Item("360", "Makke's flick.", noscoping=["set", True], weaponDamage=["mult", 1.5], weaponHandling=["mult", 1.2]),
        Item("Latex Suit", "Insulates against energy, for the freaks.", defenceEnergy=["mult", 1.4], speedMod=["mult", 0.85]),
        Item("Bayonet", "Stabs harder.", meleeDamage=["add", 0.25], weaponHandling=["mult", 0.9]),
        Item("Compressor", "Straight outta PUBG.", recoilMult=["mult", 2]),
        Item("Flash Hider", "Straight outta PUBG.", recoilMult=["mult", 1.5], weaponDamage=["add", 0.2]),
        Item("AP Rounds", "When shooting enemies, allies are just in the way.", piercing=["set", True]),
        Item("A Liter of Spit", "If you were paid 200 bucks…", healthCapMult=["add", 0.5]),
        Item("Kamikaze", "Peace is the best weapon.", detonation=["set", True], defenceExplosion=["mult", 5]),
        Item("Tank", "These guys aren't the fastest.", speedMod=["mult", 0.5], healthCapMult=["mult", 2]),
        Item("Rockman", "Rockman is a hard man.", tripChance=["add", 0.01], defenceNormal=["mult", 3], defenceEnergy=["mult", 3], defenceExplosion=["mult", 3]),
        Item("Nike Bag", "The agony of choice.", extraItem=["set", True]),
        Item("Magnet", "How do they work?", homing=["set", True], weaponDamage=["mult", 0.75]),
        Item("Shitpants", "Now you gotta move carefully.", shitChance=["add", 0.025], speedMod=["mult", 0.9], healthCapMult=["mult", 1.1]),
        Item("Double Powder", "Gun kicks like hell.", recoilMult=["mult", 0.25], weaponDamage=["mult", 2]),
        Item("Boombox", "Bulgarian pop idol.", playMusic=["set", True], dodgeChance=["add", 0.3]),
        Item("Mercedes Emblem", "Visva. Damn it.", speedMod=["mult", 1.25]),
    ]




itemEffects = {
    "speedMod": 1.0, # Done
    "healthRegenMult": 1.0,
    "thorns": 0.0,
    "healthCapMult": 1.0,
    "berserker" : False,
    "martyrdom" : False,

    "weaponHandling" : 1.0,
    "weaponDamage" : 1.0,
    "weaponReload" : 1.0,
    "weaponFireRate" : 1.0,
    "weaponAmmoCap" : 1.0,
    "weaponRange":1.0,
    "accuracy":1.0,

    "instaHeal" : False,
    "saveChance" : 0.0,
    "fireRateIncrease" : 0,
    "allyProtection" : False,
    "coward" : False,
    "revenge" : False,
    "duplicator" : False,

    "defenceNormal" : 1.0,
    "defenceEnergy" : 1.0,
    "defenceExplosion" : 1.0,

    "dodgeChance": 0.0,
    "xpMult":1.0,
    "healOnKill":0.0,
    "knockBackMult":1.0,
    "healAllies":0.0

}